language: android

jdk:
  -oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    
    - build-tools-27.0.3
    - android-27
    - extra

deploy:
  provider: heroku
  api_key:
    secure: "d46b9c26-6deb-46f5-97fd-d70b1b7ca63d"
  app: healthservice2
  strategy: git

