language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-22
    - android-24
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository

deploy:
  provider: heroku
  api_key: d46b9c26-6deb-46f5-97fd-d70b1b7ca63d
  app: healthservice2

script: ./gradlew connectedAndroidTest
