language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.3
    - tools
    - android-22
    - android-27
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository

before_install:
- yes | sdkmanager "platforms;android-27"

deploy:
  provider: heroku
  api_key: d46b9c26-6deb-46f5-97fd-d70b1b7ca63d
  app: healthservice2

script: ./gradlew clean assembleDebug
